# Generated by Django 4.1.3 on 2022-11-17 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpPersonalDetails',
            fields=[
                ('regid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('phoneNo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EmpWorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('fromDate', models.CharField(max_length=100)),
                ('toDate', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EmpWorkExperience', to='emp.emppersonaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='EmpQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualificationName', models.CharField(max_length=100)),
                ('percentage', models.FloatField()),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='EmpQualification', to='emp.emppersonaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='EmpProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EmpProjects', to='emp.emppersonaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='EmpAddressDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hno', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='EmpAddressDetails', to='emp.emppersonaldetails')),
            ],
        ),
    ]
