# Generated by Django 4.1.3 on 2022-11-17 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empqualification',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EmpQualification', to='emp.emppersonaldetails'),
        ),
    ]
