# Generated by Django 4.1.3 on 2022-11-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_empphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empphoto',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='empphoto'),
        ),
    ]
