# Generated by Django 4.1.3 on 2022-11-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_alter_empphoto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emppersonaldetails',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='empphoto'),
        ),
    ]
