# Generated by Django 4.1.3 on 2022-11-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0006_alter_empaddressdetails_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empworkexperience',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empworkexperience',
            name='fromDate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empworkexperience',
            name='toDate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
