# Generated by Django 4.1.3 on 2022-11-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0007_alter_empworkexperience_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empworkexperience',
            name='companyName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
