# Generated by Django 4.1.3 on 2022-11-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0008_alter_empworkexperience_companyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empworkexperience',
            name='companyName',
            field=models.CharField(default='mycom', max_length=100),
            preserve_default=False,
        ),
    ]
