# Generated by Django 4.1.3 on 2022-11-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0009_alter_empworkexperience_companyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empworkexperience',
            name='companyName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
